name: Deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:runner-latest
      volumes:
        - act-toolcache:/opt/hostedtoolcache
      env:
        DOTNET_INSTALL_DIR: /opt/hostedtoolcache/dotnet
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    timeout-minutes: 5
    name: Deploy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: 10.x
      - name: install gitversion
        uses: gittools/actions/gitversion/setup@bc6623af8fc07d5a8903052dd46da33403eec8e8
        with:
          versionSpec: "6.7.0"
      - name: determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@bc6623af8fc07d5a8903052dd46da33403eec8e8
        with:
          useConfigFile: true
      - uses: cardinalby/export-env-action@4f48c4676cf6ed6f46e30899ee987ce695da7c80
        id: env
        with:
          envFile: ".env"
          export: false
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version: ${{ steps.env.outputs.BUN_VERSION }}
          no-cache: true
      - name: Set package.json version
        run: bun pm version --no-git-tag-version "${{steps.gitversion.outputs.fullSemVer}}"
      - name: bun install --production
        working-directory: .scripts
        run: bun install --production
      - name: generate_all_json
        run: bun .scripts/generate_all_json
      - name: generate_id_schemas
        run: bun .scripts/generate_id_schemas
      - name: generate_other_schemas
        run: bun .scripts/generate_other_schemas
      - name: validate schemas
        run: bun .scripts/validate
      - name: compile schemas
        run: bun .scripts/compile_schemas.js
      - name: generate typescript api types
        run: find schemas/**/*.json | xargs -n1 -P0 bun .scripts/generate_api_ts.ts
      - name: generate search indexes
        run: bun .scripts/generate_search_indexes.js
      - name: generate health file
        run: bun .scripts/generate_health.js
      - name: run biome check over api
        run: bunx biome check api/ --write
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          mkdir -p ./dist
          rsync --archive --exclude-from='.scripts/dist-exclude.txt' ./ ./dist/
      - run: pip install s3cmd
      - name: Publish
        run: s3cmd sync --no-mime-magic --guess-mime-type --access_key=${{ secrets.AWS_ACCESS_KEY_ID_DEV }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }} --host=${{ secrets.AWS_ENDPOINT_URL_DEV }} --host-bucket=${{ secrets.AWS_ENDPOINT_URL_DEV }} --bucket-location=auto --delete-removed --delete-after --no-preserve --recursive ./dist 's3://lohdata-dev'
        if: ${{ github.ref == 'refs/heads/develop' }}
      - name: Publish
        run: s3cmd sync --no-mime-magic --guess-mime-type --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} --host=${{ secrets.AWS_ENDPOINT_URL }} --host-bucket=${{ secrets.AWS_ENDPOINT_URL }} --bucket-location=auto --delete-removed --delete-after --no-preserve --recursive ./dist 's3://lohdata'
        if: ${{ github.ref == 'refs/heads/master' }}